version: "3.0"

services:
  mysql-database:
    image: mysql
    container_name: boec-db
    volumes:
      - db_boec:/var/lib/mysql
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: boec
      MYSQL_USER: boec-leonard
      MYSQL_PASSWORD: aibles#2021
volumes:
  db_boec: {}