# Generated by Django 3.2.4 on 2021-06-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberHouse', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('district', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FullName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=256)),
                ('midName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.account')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.address')),
                ('fullName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.fullname')),
            ],
        ),
    ]
