# Generated by Django 3.2.4 on 2021-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boec', '0002_book_cart_clothes_electronic_item_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
