# Generated by Django 3.2.4 on 2021-06-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boec', '0003_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
