# Generated by Django 3.2.4 on 2021-06-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boec', '0007_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boec.product'),
        ),
    ]
