# Generated by Django 3.2.4 on 2021-06-17 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boec', '0009_cart_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(null=True)),
                ('total', models.FloatField(null=True)),
                ('code', models.CharField(max_length=256, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.item')),
            ],
        ),
    ]
