# Generated by Django 3.2.4 on 2021-06-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boec', '0010_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
    ]
