# Generated by Django 3.2.4 on 2021-06-18 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boec', '0011_rename_customer_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(null=True)),
                ('type', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(max_length=256, null=True)),
                ('receiveDate', models.DateField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.order')),
            ],
        ),
    ]
