# Generated by Django 3.2.4 on 2021-06-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boec', '0012_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(null=True)),
                ('paymentDate', models.DateField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.order')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boec.payment')),
                ('bankName', models.CharField(max_length=256)),
                ('accountNumber', models.CharField(max_length=256)),
            ],
            bases=('boec.payment',),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boec.payment')),
                ('nameOnCard', models.CharField(max_length=256)),
                ('cardNumber', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
            ],
            bases=('boec.payment',),
        ),
    ]
