# Generated by Django 3.2.4 on 2021-06-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boec', '0013_banktransfer_creditcard_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
