# Generated by Django 3.2.4 on 2021-06-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boec', '0016_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='status',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
