# Generated by Django 3.2.4 on 2021-06-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boec', '0017_productreview_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewProcessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processedDate', models.DateField(null=True)),
                ('status', models.CharField(max_length=256)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.employee')),
                ('productReview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boec.productreview')),
            ],
        ),
    ]
